### ISSUE TITLE
Week 1 Review Ticket

### ISSUE THREAD

**Issue by dtsivkovski** [LindaLiu1202/just_here_to_code#5]
## Week Plan
Work on two of the major website parts for the week (See issues below): 
- #2 
- #4 
- #3 

## Requirements: 2/2
Scrum Team GitHub pages (2 points)
- [x] Project Owner initial requirements, contact info, and derivative tangible plans (see github pages)
- [x] Requirements and Jobs assigned to each individuals listed on Scrum Board, including at least one in progress task (see github pages)

**Comment by jm1021** [comment]
CTE site.   Reviewed layout and made adjustments.  Thinking about less navigation, bullets represent sponsored requirement.  Ideation is reducing requirements.  Built wires for home page.    Events into a database.   UML diagram for data in events or other areas.  

1.9/2
