### ISSUE TITLE
Week 2 Review Ticket

### ISSUE THREAD

**Issue by dtsivkovski** [LindaLiu1202/just_here_to_code#8]
## Scrum Team GitHub pages (2 points) - [Link](https://lindaliu1202.github.io/just_here_to_code/)
- [x] Project Owner / Sponsor presentation(visuals like wireframes or HTML pages), results of review, PII concerns, hosting plan, and software license
- [x] 1st Code in GitHub with software license per 5.5 - [Link to license](https://github.com/LindaLiu1202/just_here_to_code/blob/main/LICENSE)

## Issues this week:
- #3 
- #4 
- #6 
- #7

**Comment by jm1021** [comment]
CTE webpage and course advertising.  

Deployment:   Temporarily local.  AWS under Poway District is ultimate.

License rationale may not be what is required.

UML / User Experience diagram is shared.  Half data and half workflow.

Wireframes. Colors and themes discussed.  

Real pages have bootstrap modal and a little less travel between sites.  

Event calendar shared, looks like a reverse linear list.   

Question about main purpose.  Answer Information and Events.

Suggestion Question and Answer.

Review of style.  Cards seems to be choice.

**Comment by jm1021** [comment]
As a Teacher, I need to learn to reward failure and effort in projects. The idea of each build is to see students take risks. Not necessarily produce something immediately useful or final, but leading to utility.

This project has great utility and CTE wants you to be successful.  This is a great opportunity for team and this project could be a great advantage to all of you if you continue to CSA or participate in nighthawkcodingsociety.  Concern I have is information as-is by CTE is connected to PUSD site and standards.   Are these the links you are working from?
https://www.powayusd.com/cte?fbclid=IwAR09eX6M-JXVVe_gT9XC3_BMPeoONbAtyKxJLTT9DoRFmqXbpAhS2Ve99WQ
https://www.facebook.com/PowayCTE/

WRT your ideas, you had confirmation from crossover that the bootstrap modal makes thing seem much more fluid or connected. 
1. CTE staff should be able to add and create a new Modal and populate some initial messaging without coding.  However, it may not all be database driven, they may be able to update using MarkDown given training.
2. IMO each Modal should be a resulting More or Detail page should probably have ability to update an area from initial messaging and modal information.  Next comment shows detail page.

**Comment by jm1021** [comment]
Next level of information.  This is a pretty dead page and it is related to me.

https://www.powayusd.com/en-US/Departments/CareerTechnicalAdultEd/College-Career-Technical-Education/Industry-Sectors/Information-Communication-Technology

You can see several others in side bar.  Also, as a thought my twitter could be a part of CTE network.  A true CTE IMO should include ability for students (when given permission) to add and communicate in their sectors.  Like you in Information and Communication Technology.  Currently Facebook seems like one form of communication for everyone.
